baseURL = "https://www.dos4dev.com/"
languageCode = "en-us"
title = "Oleksii Danyliuk"
theme = "ezhil"
copyright = "© 2021 Oleksii Danyliuk"


[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "Thoughts on digital society and related things."
	# Number of posts to show in recent posts list (Optional). Defaults to 10.
	recentPostsCount = 10
	# Content types which are included in home page recent posts list.
	mainSections = ["blog"]
	# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
	# Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
	disableDisqusTypes = ["page"]
	# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true

	# searchURL = "http://localhost:8080/"
	searchURL = "https://search.gunnar-morling.workers.dev/Prod/"
	apiKey = "ff90d45f4afad3bd914c"

	# Custom CSS added to default styles. Files added to `static` folder is copied as it is to
	# root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
	# you can specify custom css path as `css/custom.css`.
	# Rouge CSS files (syntax highlighter used by AsciiDoctor) are obtained via
	# rougify style base16.dark > static/css/base16.dark.css
	customCSS = ["css/base16.dark.css", "css/morlingdev.css"]

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

# [[menu.main]]
# name = "Projects"
# url = "/projects/"
# weight = 2

# [[menu.main]]
# name = "Conferences"
# url = "/conferences/"
# weight = 3

# [[menu.main]]
# name = "Podcasts"
# url = "/podcasts/"
# weight = 4

[[menu.main]]
name = "About"
url = "/about/"
weight = 5


# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).

# todo: https://github.com/Dos4dev/dos4dev.com/projects/1#card-74614163
# [[params.social]]
# name = "RSS FEED"
# icon = "rss"
# url = "/blog/index.xml"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Dos4dev"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/Dos4dev"

[[params.social]]
name = "Stackoverflow"
icon = "align-justify"
url = "https://stackoverflow.com/users/9183844/dos4dev"

[[params.social]]
name = "Hackerrank"
icon = "zap"
url = "https://www.hackerrank.com/dos4dev"


# Enable tags.
# [taxonomies]
# tag = "tags"

[privacy.youtube]
privacyEnhanced = true

[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML","RSS", "SearchIndex"]
